const jobs = [
    {
        job_title: "Associate Software Engineer",
        company: "Ey",
        location: "Bengaluru",
        experience: "Fresher",
        education: "B.Tech",
        skills: ["Python", "Java", "SQL"],
    },
    {
        job_title: "Quality Automation Engineer (SDET) / Technology Engineering Trainee",
        company: "Equifax",
        location: "Pune",
        experience: "Fresher - 2 Years",
        education: "Other",
        skills: ["Artificial Intelligence", "Cloud Computing"],
    },
    {
        job_title: "Machine Learning Engineer",
        company: "Expedia",
        location: "Bangalore",
        experience: "Fresher - 2 years",
        education: "Bachelors",
        skills: ["Python", "Java", "AWS"],
    },
    {
        job_title: "Software Development Engineer",
        company: "Amazon",
        location: "Bangalore",
        experience: "Fresher",
        education: "Bachelors",
        skills: ["Python", "Java", "C++"],
    },
    {
        job_title: "NATA Trainee",
        company: "Invesco",
        location: "Hyderabad",
        experience: "Fresher",
        education: "MBA",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "2026 Campus Hire_ Associate Engineer_ HW",
        company: "Qualcomm",
        location: "Hyderabad / Bangalore / Chennai / Noida",
        experience: "Fresher",
        education: "B.Tech",
        skills: ["C++"],
    },
    {
        job_title: "Analyst- Learning Operations / Reporting & Analytics - Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        experience: "Fresher - 3 Years",
        education: "B.Tech",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "Associate Support Engineer",
        company: "Precisely",
        location: "Bangalore / Pune",
        experience: "Fresher - 1 Year",
        education: "B.Tech",
        skills: ["Python", "Java", "C++", "SQL", "AWS", "Azure"],
    },
    {
        job_title: "Associate Analyst - Operations Performance & Analytics",
        company: "United Airlines",
        location: "Gurugram",
        experience: "Fresher - 1 Year",
        education: "Bachelors",
        skills: ["Python", "SQL", "Data Analysis"],
    },
    {
        job_title: "Junior Engineer",
        company: "Cornerstone",
        location: "Pune",
        experience: "Fresher",
        education: "Bachelors",
        skills: ["Java", "SQL"],
    },
    {
        job_title: "Associate Software Engineer",
        company: "S&P Global",
        location: "Ahmedabad",
        experience: "Fresher - 2 Years",
        education: "B.Tech",
        skills: ["Python", "Java", "SQL", "AWS", "Azure"],
    },
    {
        job_title: "Junior Engineer",
        company: "Flex",
        location: "Chennai",
        experience: "Fresher - 2 Years",
        education: "Other",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "Graduate Software Engineer",
        company: "HP Enterprise",
        location: "Bangalore",
        experience: "Fresher - 2 Years",
        education: "B.Tech",
        skills: ["Python", "Java", "JavaScript"],
    },
    {
        job_title: "Graduate Engineer Trainee",
        company: "Johnson Controls",
        location: "Pune",
        experience: "Fresher",
        education: "",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "Graduate Engineer Trainee",
        company: "GE Healthcare",
        location: "Bengaluru / Lucknow",
        experience: "Fresher",
        education: "Bachelors",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "Software Engineer",
        company: "Nike",
        location: "Bangalore",
        experience: "Not specified",
        education: "Bachelors",
        skills: ["Python", "Java", "SQL", "AWS"],
    },
    {
        job_title: "Technical Support Associate / Technical Engineer - Problem Setter (Programming ) - Internship",
        company: "Hackerearth",
        location: "Bangalore",
        experience: "Fresher",
        education: "Other",
        skills: ["SQL"],
    },
    {
        job_title: "Software Engineer - (Summer Internship)",
        company: "Cisco",
        location: "Bangalore",
        experience: "Fresher",
        education: "Other",
        skills: ["Artificial Intelligence"],
    },
    {
        job_title: "Graduate Engineer Trainee - Testing",
        company: "Rockwell Automation",
        location: "Bangalore",
        experience: "Fresher",
        education: "Other",
        skills: ["Python", "SQL"],
    },
    {
        job_title: "Software Engineer",
        company: "Microsoft",
        location: "PAN India",
        experience: "Entry Level",
        education: "B.Tech",
        skills: ["Python", "Java", "C++", "JavaScript"],
    },
];

export default jobs;
